version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: business-intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/bis_intel/data
    networks:
      - bis-intel-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bis_intel/data
    networks:
      - bis-intel-network

volumes:
  postgres_data:
  redis_data:

networks:
  bis-intel-network:
